import jsPDF from 'jspdf';
import { getImageDimensions, fitBox, detectImageFormat } from './logo-utils';

interface DischargeSummaryPdfData {
  hospitalName: string;
  hospitalLogo?: string | null;
  hospitalPhone?: string;
  hospitalEmail?: string;
  hospitalAddress?: string;
  hospitalCity?: string;
  patientName: string;
  patientMrn: string;
  wardName?: string | null;
  bedNumber?: string | null;
  admittedAt: string;
  dischargedAt: string;
  admittingDoctor?: string | null;
  dischargeDiagnosis?: string | null;
  dischargeSummary?: string | null;
  followUpInstructions?: string | null;
}

async function buildDischargeSummaryDoc(data: DischargeSummaryPdfData): Promise<jsPDF> {
  const doc = new jsPDF();

  const HEADER_TOP = 10;
  const LOGO_BOX = 20;
  let titleX = 14;

  if (data.hospitalLogo) {
    try {
      const { width, height } = await getImageDimensions(data.hospitalLogo);
      const { w, h } = fitBox(width, height, 18);
      const logoY = HEADER_TOP + (LOGO_BOX - h) / 2;
      doc.addImage(data.hospitalLogo, detectImageFormat(data.hospitalLogo), 14, logoY, w, h);
      titleX = 14 + LOGO_BOX + 4;
    } catch {
      // Malformed/unsupported image data — fall back to text-only header
    }
  }

  doc.setFontSize(18);
  doc.setTextColor(30, 41, 59);
  doc.text(data.hospitalName, titleX, 20);

  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  const contactLine = [data.hospitalPhone, data.hospitalEmail].filter(Boolean).join('  •  ');
  const addressLine = [data.hospitalAddress, data.hospitalCity].filter(Boolean).join(', ');
  if (contactLine) doc.text(contactLine, titleX, 26);
  if (addressLine) doc.text(addressLine, titleX, 31);

  doc.setFontSize(13);
  doc.setTextColor(100, 116, 139);
  doc.text('DISCHARGE SUMMARY', 196, 20, { align: 'right' });

  doc.setDrawColor(226, 232, 240);
  doc.line(14, 36, 196, 36);

  let y = 46;
  doc.setFontSize(10);
  doc.setTextColor(30, 41, 59);
  doc.text('Patient:', 14, y);
  doc.setFontSize(11);
  doc.text(data.patientName, 40, y);
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`MRN: ${data.patientMrn}`, 40, y + 5);

  doc.setFontSize(10);
  doc.setTextColor(30, 41, 59);
  doc.text('Bed/Ward:', 120, y);
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`${data.wardName || '—'}${data.bedNumber ? ` (Bed ${data.bedNumber})` : ''}`, 145, y);

  y += 16;
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text('Admitted:', 14, y);
  doc.setTextColor(30, 41, 59);
  doc.text(new Date(data.admittedAt).toLocaleString(), 40, y);

  doc.setTextColor(100, 116, 139);
  doc.text('Discharged:', 120, y);
  doc.setTextColor(30, 41, 59);
  doc.text(new Date(data.dischargedAt).toLocaleString(), 148, y);

  if (data.admittingDoctor) {
    y += 6;
    doc.setTextColor(100, 116, 139);
    doc.text('Doctor:', 14, y);
    doc.setTextColor(30, 41, 59);
    doc.text(`Dr. ${data.admittingDoctor}`, 40, y);
  }

  y += 12;

  const addSection = (label: string, content?: string | null) => {
    if (!content) return;
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);
    doc.setFont('helvetica', 'bold');
    doc.text(label, 14, y);
    doc.setFont('helvetica', 'normal');
    y += 6;
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    const lines = doc.splitTextToSize(content, 175);
    doc.text(lines, 14, y);
    y += lines.length * 5 + 8;
  };

  addSection('Discharge Diagnosis', data.dischargeDiagnosis);
  addSection('Discharge Summary', data.dischargeSummary);
  addSection('Follow-up Instructions', data.followUpInstructions);

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by PLYXIO Vitals', 14, 285);

  return doc;
}

export async function generateDischargeSummaryPdf(data: DischargeSummaryPdfData) {
  const doc = await buildDischargeSummaryDoc(data);
  doc.save(`Discharge-Summary-${data.patientMrn}.pdf`);
}

export async function printDischargeSummaryPdf(data: DischargeSummaryPdfData) {
  const win = window.open('', '_blank');
  const doc = await buildDischargeSummaryDoc(data);
  const blobUrl = doc.output('bloburl');
  if (win) {
    win.location.href = blobUrl as unknown as string;
    win.addEventListener('load', () => win.print());
  }
}
