import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface InvoicePdfData {
  hospitalName: string;
  hospitalLogo?: string | null;
  hospitalPhone?: string;
  hospitalEmail?: string;
  hospitalAddress?: string;
  hospitalCity?: string;
  currencySymbol?: string;
  taxLabel?: string;
  invoiceNo: string;
  createdAt: string;
  status: string;
  patientName: string;
  patientMrn: string;
  items: { description: string; category?: string; quantity: number; unitPrice: number; amount: number }[];
  subtotal: number;
  discount: number;
  tax: number;
  total: number;
  amountPaid: number;
}

function buildInvoiceDoc(data: InvoicePdfData): jsPDF {
  const doc = new jsPDF();
  const balance = data.total - data.amountPaid;
  const currency = data.currencySymbol || 'Rs';
  const taxLabel = data.taxLabel || 'Tax';
  let titleX = 14;

  if (data.hospitalLogo) {
    try {
      const fmt = data.hospitalLogo.includes('image/jpeg') || data.hospitalLogo.includes('image/jpg') ? 'JPEG' : 'PNG';
      doc.addImage(data.hospitalLogo, fmt, 14, 12, 16, 16);
      titleX = 34;
    } catch {
      // Malformed/unsupported image data — fall back to text-only header
    }
  }

  doc.setFontSize(18);
  doc.setTextColor(30, 41, 59);
  doc.text(data.hospitalName, titleX, 20);

  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  const contactLine = [data.hospitalPhone, data.hospitalEmail].filter(Boolean).join('  •  ');
  const addressLine = [data.hospitalAddress, data.hospitalCity].filter(Boolean).join(', ');
  if (contactLine) doc.text(contactLine, titleX, 26);
  if (addressLine) doc.text(addressLine, titleX, 31);

  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.text('INVOICE', 196, 20, { align: 'right' });
  doc.text(data.invoiceNo, 196, 26, { align: 'right' });
  doc.text(new Date(data.createdAt).toLocaleDateString(), 196, 32, { align: 'right' });

  doc.setDrawColor(226, 232, 240);
  doc.line(14, 38, 196, 38);

  doc.setFontSize(10);
  doc.setTextColor(30, 41, 59);
  doc.text('Billed to:', 14, 48);
  doc.setFontSize(11);
  doc.text(data.patientName, 14, 54);
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`MRN: ${data.patientMrn}`, 14, 59);

  doc.setFontSize(10);
  doc.setTextColor(30, 41, 59);
  doc.text(`Status: ${data.status.replace('_', ' ')}`, 196, 48, { align: 'right' });

  autoTable(doc, {
    startY: 68,
    head: [['Description', 'Category', 'Qty', 'Unit Price', 'Amount']],
    body: data.items.map((it) => [
      it.description,
      it.category || '—',
      String(it.quantity),
      `${currency} ${it.unitPrice.toLocaleString()}`,
      `${currency} ${it.amount.toLocaleString()}`,
    ]),
    headStyles: { fillColor: [99, 102, 241] },
    styles: { fontSize: 9 },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 10;
  const summaryX = 140;
  const summaryLines: [string, string][] = [
    ['Subtotal', `${currency} ${data.subtotal.toLocaleString()}`],
    ['Discount', `-${currency} ${data.discount.toLocaleString()}`],
    [taxLabel, `+${currency} ${data.tax.toLocaleString()}`],
    ['Total', `${currency} ${data.total.toLocaleString()}`],
    ['Paid', `${currency} ${data.amountPaid.toLocaleString()}`],
    ['Balance', `${currency} ${balance.toLocaleString()}`],
  ];

  let y = finalY;
  doc.setFontSize(10);
  for (const [label, value] of summaryLines) {
    const isTotal = label === 'Total' || label === 'Balance';
    doc.setFont('helvetica', isTotal ? 'bold' : 'normal');
    doc.setTextColor(isTotal ? 15 : 100, isTotal ? 23 : 116, isTotal ? 42 : 139);
    doc.text(label, summaryX, y);
    doc.text(value, 196, y, { align: 'right' });
    y += 7;
  }

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by PLYXIO Vitals', 14, 285);

  return doc;
}

export function generateInvoicePdf(data: InvoicePdfData) {
  buildInvoiceDoc(data).save(`${data.invoiceNo}.pdf`);
}

export function printInvoicePdf(data: InvoicePdfData) {
  const doc = buildInvoiceDoc(data);
  const blobUrl = doc.output('bloburl');
  const win = window.open(blobUrl as unknown as string, '_blank');
  win?.addEventListener('load', () => win.print());
}
