import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { getImageDimensions, fitBox, detectImageFormat } from './logo-utils';

interface LedgerPdfData {
  hospitalName: string;
  hospitalLogo?: string | null;
  periodLabel: string;
  currencySymbol: string;
  transactions: { date: string; type: string; description: string; category: string; amount: number }[];
  totalIn: number;
  totalOut: number;
}

export async function generateLedgerPdf(data: LedgerPdfData) {
  const doc = new jsPDF();
  const currency = data.currencySymbol;

  const HEADER_TOP = 10;
  const LOGO_BOX = 20;
  let titleX = 14;

  if (data.hospitalLogo) {
    try {
      const { width, height } = await getImageDimensions(data.hospitalLogo);
      const { w, h } = fitBox(width, height, 18);
      const logoY = HEADER_TOP + (LOGO_BOX - h) / 2;
      doc.addImage(data.hospitalLogo, detectImageFormat(data.hospitalLogo), 14, logoY, w, h);
      titleX = 14 + LOGO_BOX + 4;
    } catch {
      // Malformed/unsupported image data — fall back to text-only header
    }
  }

  doc.setFontSize(18);
  doc.setTextColor(30, 41, 59);
  doc.text(data.hospitalName, titleX, 20);

  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.text('LEDGER STATEMENT', 196, 20, { align: 'right' });
  doc.text(data.periodLabel, 196, 26, { align: 'right' });

  doc.setDrawColor(226, 232, 240);
  doc.line(14, 34, 196, 34);

  autoTable(doc, {
    startY: 42,
    head: [['Date', 'Type', 'Description', 'Category', 'Amount']],
    body: data.transactions.map((t) => [
      new Date(t.date).toLocaleDateString(),
      t.type,
      t.description,
      t.category,
      `${t.amount < 0 ? '-' : ''}${currency} ${Math.abs(t.amount).toLocaleString()}`,
    ]),
    headStyles: { fillColor: [99, 102, 241] },
    styles: { fontSize: 8 },
    columnStyles: { 4: { halign: 'right' } },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 10;
  const net = data.totalIn - data.totalOut;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text('Total In', 140, finalY);
  doc.text(`${currency} ${data.totalIn.toLocaleString()}`, 196, finalY, { align: 'right' });
  doc.text('Total Out', 140, finalY + 7);
  doc.text(`${currency} ${data.totalOut.toLocaleString()}`, 196, finalY + 7, { align: 'right' });

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(net >= 0 ? 15 : 185, net >= 0 ? 118 : 28, net >= 0 ? 110 : 28);
  doc.text('Net', 140, finalY + 16);
  doc.text(`${currency} ${net.toLocaleString()}`, 196, finalY + 16, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by PLYXIO Vitals', 14, 285);

  doc.save(`Ledger-${data.periodLabel.replace(/\s+/g, '-')}.pdf`);
}
