import jsPDF from 'jspdf';
import { getImageDimensions, fitBox, detectImageFormat } from './logo-utils';

interface MedicalCertificatePdfData {
  hospitalName: string;
  hospitalLogo?: string | null;
  hospitalPhone?: string;
  hospitalEmail?: string;
  hospitalAddress?: string;
  hospitalCity?: string;
  patientName: string;
  patientMrn: string;
  doctorName: string;
  doctorSpecialty?: string | null;
  type: string;
  startDate: string;
  endDate: string;
  reason?: string | null;
  notes?: string | null;
  issuedAt: string;
}

const TYPE_LABELS: Record<string, string> = {
  SICK_LEAVE: 'MEDICAL CERTIFICATE — SICK LEAVE',
  FITNESS: 'CERTIFICATE OF FITNESS',
  OTHER: 'MEDICAL CERTIFICATE',
};

async function buildCertificateDoc(data: MedicalCertificatePdfData): Promise<jsPDF> {
  const doc = new jsPDF();

  const HEADER_TOP = 10;
  const LOGO_BOX = 20;
  let titleX = 14;

  if (data.hospitalLogo) {
    try {
      const { width, height } = await getImageDimensions(data.hospitalLogo);
      const { w, h } = fitBox(width, height, 18);
      const logoY = HEADER_TOP + (LOGO_BOX - h) / 2;
      doc.addImage(data.hospitalLogo, detectImageFormat(data.hospitalLogo), 14, logoY, w, h);
      titleX = 14 + LOGO_BOX + 4;
    } catch {
      // Malformed/unsupported image data — fall back to text-only header
    }
  }

  doc.setFontSize(18);
  doc.setTextColor(30, 41, 59);
  doc.text(data.hospitalName, titleX, 20);

  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  const contactLine = [data.hospitalPhone, data.hospitalEmail].filter(Boolean).join('  •  ');
  const addressLine = [data.hospitalAddress, data.hospitalCity].filter(Boolean).join(', ');
  if (contactLine) doc.text(contactLine, titleX, 26);
  if (addressLine) doc.text(addressLine, titleX, 31);

  doc.setDrawColor(226, 232, 240);
  doc.line(14, 38, 196, 38);

  doc.setFontSize(15);
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'bold');
  doc.text(TYPE_LABELS[data.type] || TYPE_LABELS.OTHER, 105, 52, { align: 'center' });
  doc.setFont('helvetica', 'normal');

  let y = 68;
  doc.setFontSize(11);
  doc.setTextColor(30, 41, 59);

  const days = Math.max(1, Math.round((new Date(data.endDate).getTime() - new Date(data.startDate).getTime()) / (1000 * 60 * 60 * 24)) + 1);

  const bodyLines = doc.splitTextToSize(
    `This is to certify that ${data.patientName} (MRN: ${data.patientMrn}) was examined by the undersigned and is advised ` +
    `${data.type === 'FITNESS' ? 'to be fit to resume normal duties' : 'rest'} from ${new Date(data.startDate).toLocaleDateString()} ` +
    `to ${new Date(data.endDate).toLocaleDateString()} (${days} day${days > 1 ? 's' : ''}).`,
    170
  );
  doc.text(bodyLines, 20, y);
  y += bodyLines.length * 6 + 8;

  if (data.reason) {
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text('Reason:', 20, y);
    doc.setTextColor(30, 41, 59);
    const reasonLines = doc.splitTextToSize(data.reason, 165);
    doc.text(reasonLines, 45, y);
    y += reasonLines.length * 5 + 8;
  }

  if (data.notes) {
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text('Notes:', 20, y);
    doc.setTextColor(30, 41, 59);
    const notesLines = doc.splitTextToSize(data.notes, 165);
    doc.text(notesLines, 45, y);
    y += notesLines.length * 5 + 8;
  }

  y += 20;
  doc.setDrawColor(150, 150, 150);
  doc.line(20, y, 90, y);
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`Dr. ${data.doctorName}`, 20, y + 5);
  if (data.doctorSpecialty) doc.text(data.doctorSpecialty, 20, y + 10);

  doc.text(`Issued: ${new Date(data.issuedAt).toLocaleDateString()}`, 150, y + 5);

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by PLYXIO Vitals', 14, 285);

  return doc;
}

export async function generateMedicalCertificatePdf(data: MedicalCertificatePdfData) {
  const doc = await buildCertificateDoc(data);
  doc.save(`Medical-Certificate-${data.patientMrn}.pdf`);
}

export async function printMedicalCertificatePdf(data: MedicalCertificatePdfData) {
  const win = window.open('', '_blank');
  const doc = await buildCertificateDoc(data);
  const blobUrl = doc.output('bloburl');
  if (win) {
    win.location.href = blobUrl as unknown as string;
    win.addEventListener('load', () => win.print());
  }
}
