import { User, Patient, Doctor, Appointment, Bill, InventoryItem, Staff } from './types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'admin-1',
    email: 'admin@hospital.com',
    password: 'admin123',
    name: 'Admin User',
    role: 'admin',
    phone: '555-0001',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'doctor-1',
    email: 'dr.smith@hospital.com',
    password: 'doctor123',
    name: 'Dr. James Smith',
    role: 'doctor',
    phone: '555-0002',
    department: 'Cardiology',
    createdAt: new Date('2024-01-05'),
  },
  {
    id: 'doctor-2',
    email: 'dr.johnson@hospital.com',
    password: 'doctor123',
    name: 'Dr. Sarah Johnson',
    role: 'doctor',
    phone: '555-0003',
    department: 'Orthopedics',
    createdAt: new Date('2024-01-06'),
  },
  {
    id: 'patient-1',
    email: 'john@example.com',
    password: 'patient123',
    name: 'John Doe',
    role: 'patient',
    phone: '555-1001',
    createdAt: new Date('2024-01-10'),
  },
  {
    id: 'patient-2',
    email: 'jane@example.com',
    password: 'patient123',
    name: 'Jane Wilson',
    role: 'patient',
    phone: '555-1002',
    createdAt: new Date('2024-01-12'),
  },
  {
    id: 'staff-1',
    email: 'nurse1@hospital.com',
    password: 'staff123',
    name: 'Maria Garcia',
    role: 'staff',
    phone: '555-2001',
    department: 'Nursing',
    createdAt: new Date('2024-01-15'),
  },
];

// Mock Patients
export const mockPatients: Patient[] = [
  {
    id: 'p-001',
    userId: 'patient-1',
    firstName: 'John',
    lastName: 'Doe',
    dateOfBirth: '1985-05-15',
    gender: 'male',
    bloodType: 'O+',
    phone: '555-1001',
    email: 'john@example.com',
    address: '123 Main St',
    city: 'New York',
    state: 'NY',
    zipCode: '10001',
    medicalHistory: 'Hypertension, Type 2 Diabetes',
    allergies: 'Penicillin',
    emergencyContact: 'Jane Doe',
    emergencyPhone: '555-1099',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'p-002',
    userId: 'patient-2',
    firstName: 'Jane',
    lastName: 'Wilson',
    dateOfBirth: '1990-08-22',
    gender: 'female',
    bloodType: 'A+',
    phone: '555-1002',
    email: 'jane@example.com',
    address: '456 Oak Ave',
    city: 'New York',
    state: 'NY',
    zipCode: '10002',
    medicalHistory: 'Asthma',
    allergies: 'None',
    emergencyContact: 'John Wilson',
    emergencyPhone: '555-1098',
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
  },
];

// Mock Doctors
export const mockDoctors: Doctor[] = [
  {
    id: 'd-001',
    userId: 'doctor-1',
    firstName: 'James',
    lastName: 'Smith',
    specialization: 'Cardiology',
    licenseNumber: 'LIC-001',
    phone: '555-0002',
    email: 'dr.smith@hospital.com',
    department: 'Cardiology',
    yearsOfExperience: 15,
    availableSlots: ['09:00', '10:00', '14:00', '15:00'],
    consultationFee: 150,
    about: 'Board certified cardiologist with 15 years of experience',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
  {
    id: 'd-002',
    userId: 'doctor-2',
    firstName: 'Sarah',
    lastName: 'Johnson',
    specialization: 'Orthopedics',
    licenseNumber: 'LIC-002',
    phone: '555-0003',
    email: 'dr.johnson@hospital.com',
    department: 'Orthopedics',
    yearsOfExperience: 12,
    availableSlots: ['10:00', '11:00', '15:00', '16:00'],
    consultationFee: 120,
    about: 'Specialized in orthopedic surgery and rehabilitation',
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-06'),
  },
];

// Mock Appointments
export const mockAppointments: Appointment[] = [
  {
    id: 'apt-001',
    patientId: 'p-001',
    doctorId: 'd-001',
    appointmentDate: '2024-07-25',
    appointmentTime: '09:00',
    status: 'scheduled',
    reason: 'Routine check-up',
    notes: 'Patient reports chest discomfort',
    createdAt: new Date('2024-07-20'),
    updatedAt: new Date('2024-07-20'),
  },
  {
    id: 'apt-002',
    patientId: 'p-002',
    doctorId: 'd-002',
    appointmentDate: '2024-07-26',
    appointmentTime: '10:00',
    status: 'scheduled',
    reason: 'Follow-up after injury',
    notes: 'Check progress on ankle healing',
    createdAt: new Date('2024-07-20'),
    updatedAt: new Date('2024-07-20'),
  },
];

// Mock Bills
export const mockBills: Bill[] = [
  {
    id: 'bill-001',
    patientId: 'p-001',
    appointmentId: 'apt-001',
    amount: 150,
    description: 'Consultation - Cardiology',
    issueDate: '2024-07-20',
    dueDate: '2024-08-20',
    status: 'pending',
    createdAt: new Date('2024-07-20'),
    updatedAt: new Date('2024-07-20'),
  },
  {
    id: 'bill-002',
    patientId: 'p-002',
    amount: 500,
    description: 'X-ray and imaging',
    issueDate: '2024-07-15',
    dueDate: '2024-08-15',
    status: 'paid',
    paymentMethod: 'Credit Card',
    paidDate: '2024-07-18',
    createdAt: new Date('2024-07-15'),
    updatedAt: new Date('2024-07-18'),
  },
];

// Mock Inventory
export const mockInventory: InventoryItem[] = [
  {
    id: 'inv-001',
    name: 'Surgical Masks',
    category: 'PPE',
    quantity: 500,
    unit: 'boxes',
    reorderLevel: 100,
    supplier: 'MedSupply Inc',
    cost: 50,
    lastRestocked: '2024-07-15',
    createdAt: new Date('2024-07-15'),
    updatedAt: new Date('2024-07-15'),
  },
  {
    id: 'inv-002',
    name: 'Gloves (Latex)',
    category: 'PPE',
    quantity: 30,
    unit: 'boxes',
    reorderLevel: 50,
    supplier: 'MedSupply Inc',
    cost: 25,
    lastRestocked: '2024-07-10',
    createdAt: new Date('2024-07-10'),
    updatedAt: new Date('2024-07-10'),
  },
  {
    id: 'inv-003',
    name: 'Bandages (Sterile)',
    category: 'Wound Care',
    quantity: 200,
    unit: 'packs',
    reorderLevel: 100,
    supplier: 'MedSupply Inc',
    cost: 15,
    lastRestocked: '2024-07-12',
    createdAt: new Date('2024-07-12'),
    updatedAt: new Date('2024-07-12'),
  },
];

// Mock Staff
export const mockStaff: Staff[] = [
  {
    id: 'staff-001',
    userId: 'staff-1',
    firstName: 'Maria',
    lastName: 'Garcia',
    position: 'Registered Nurse',
    department: 'Nursing',
    phone: '555-2001',
    email: 'nurse1@hospital.com',
    hireDate: '2022-03-15',
    salary: 65000,
    status: 'active',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'staff-002',
    userId: 'staff-1',
    firstName: 'Robert',
    lastName: 'Martinez',
    position: 'Phlebotomist',
    department: 'Laboratory',
    phone: '555-2002',
    email: 'phlebotomist@hospital.com',
    hireDate: '2023-06-01',
    salary: 45000,
    status: 'active',
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-16'),
  },
];
